// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEfXO12UKy1F23IuIn15AX4zA3trYB_CM',
    appId: '1:876132148030:web:fb552569ce10b7f0a3026f',
    messagingSenderId: '876132148030',
    projectId: 'edupro-8c4fd',
    authDomain: 'edupro-8c4fd.firebaseapp.com',
    storageBucket: 'edupro-8c4fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9RT-c6pmIuLVx8EizFD_a3_82ffRUbTs',
    appId: '1:876132148030:android:4999d69c88109fe2a3026f',
    messagingSenderId: '876132148030',
    projectId: 'edupro-8c4fd',
    storageBucket: 'edupro-8c4fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHdD6naoa6lyfzBZVbtKlMMr5qNSFTkJE',
    appId: '1:876132148030:ios:1d1979b772e447e4a3026f',
    messagingSenderId: '876132148030',
    projectId: 'edupro-8c4fd',
    storageBucket: 'edupro-8c4fd.firebasestorage.app',
    iosBundleId: 'com.example.edupro',
  );
}
